version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.5 # Use a Docker image that has Docker installed

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |            
            sudo yum install awscli -y

      # Build your Docker image
      - run:
          name: Build Docker image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 695357413142.dkr.ecr.us-east-1.amazonaws.com
            docker build -t circleci .
            docker tag circleci:latest 695357413142.dkr.ecr.us-east-1.amazonaws.com/circleci:latest

      # Push the Docker image to a container registry
      - run:
          name: Push Docker image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 695357413142.dkr.ecr.us-east-1.amazonaws.com
            docker push 695357413142.dkr.ecr.us-east-1.amazonaws.com/circleci:latest
