version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6  # Use the CircleCI Python image or your preferred base image

    steps:
      - checkout  # Check out the code
    
      # Other steps to install dependencies, tests, etc.
      
      - run:
          name: Build Docker Image
          command: |
            docker build -t 7618/springboot_mongodb_circleci:1 .
            docker login -u 7618 -p Harman789$
            #docker tag your_image_name:tag $DOCKERHUB_USERNAME/your_image_name:tag
            docker push 7618/springboot_mongodb_circleci:1
